#!/bin/bash
#alias NICKNAME='COMMAND'

# color support
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='colordiff' #requires colordiff package

# modified commands
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias less='less -i'
alias mkdir='mkdir -pv'
alias ping='ping -c 4'
#alias ack='ack-grep'

# shortcuts
alias c='clear'
alias ccd='cd ~ && clear'
alias qq='exit'
alias ka='killall'
alias x='xinit'
alias ra='ranger'
alias db='dropbox'
alias dbp='dropbox puburl'
alias ns='notify-send'
alias nsc='notify-send "Process Completed"'
alias h='history | tail -n 25'
alias open='xdg-open'
alias lns='ln -s'
alias ..='cd ..'
#alias dua='\du -ha'
#alias dus='\du -hs'

# new commands
alias lock='xscreensaver-command -lock'              # locks the user enviroment with xscreensaver 
alias xmerge='xrdb -merge $HOME/.Xresources'         # sets resources to be used correctly by xorg
alias help='cat ~/.help'                             # prints out local help file
#alias du1='\du -h --max-depth=1 | sort -hr'         #
#alias du2='\du -h --max-depth=2'                    #
#alias du3='\du -h --max-depth=3'                    #
#alias du1a='\du -ha --max-depth=1 | sort -hr'       #
#alias du2a='\du -ha --max-depth=2'                  #
#alias du3a='\du -ha --max-depth=3'                  #
alias hist='history | grep $1'                                                        # requires an argument
#alias openports='netstat --all --numeric --programs --inet --inet6'                  #
#alias pg='ps -Af | grep $1'                                                          # requires an argument (note: /usr/bin/pg is installed by the util-linux package; maybe a different alias name should be used)
#alias pcp="rsync --partial --progress --append --rsh=ssh -r -h"                      #
#alias pmv="rsync --partial --progress --append --rsh=ssh -r -h --remove-sent-files"  #
alias sshot="scrot ~/Pictures/Screenshots/%F-%T_$wx$h.png"  # takes a screen shot with scrot and stores it in ~Pictures/Screenshots
alias dt="date +%F%nDay\ %j\ Week\ %W'.'%u%n%T"     # prints out current date in style
alias sys="uname -smrno && date +%F'\'%T && acpi"   # prints out system information as well as the current date
alias xfix='xrandr --output DVI-I-1 --left-of DVI-I-2'                                # Fixes display of xmonad for two 1920x1080 monitors
alias pb='pianobar'
alias Vup='amixer set Master 4+'
alias Vdn='amixer set Master 4-'
alias Vtg='amixer set Master toggle'
alias wpafix='sudo wpa_supplicant -iwlp1s0 -c./wpa.conf'    # Requires a configuration file ~/wpa.conf to be created with wpa_passphrase <essid> <passphrase>

# provides de-bug for troublesome xorg configuration, prints out all lines with warnings then all lines with errors
# [xo]rg [p]roblem [r]eport
alias xopr='echo "Xorg Warnings:" && cat ~/.local/share/xorg/Xorg.0.log | ack "] \(WW\)" && echo "\nXorg Errors:" && cat ~/.local/share/xorg/Xorg.0.log | ack "] \(EE\)"'

# privileged access
if [ $UID -ne 0 ]; then
    alias scat='sudo cat'
    alias svim='sudo vim'
    alias reboot='sudo systemctl reboot'
    alias poweroff='sudo systemctl poweroff'
    alias suspend='gksudo pm-suspend & lock'
    alias hibernate='gksudo pm-suspend hybrid & lock'
fi

# safety features
#alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# programming languages
alias ja='java'
alias jc='javac'
alias jca='javac *.java'
alias jrm='rm *.class'
alias rb='ruby'
alias py='python3'
alias py2='python2'

# vim
alias v='vim -p'
alias va='vim -p *'
alias vh='vim -o'
alias vv='vim -O'
alias vd='vim -d'

# feh
alias feh='feh --scale-down --auto-zoom'

# git
if command -v hub &>/dev/null; then
	alias git='hub'
	alias g='hub'
else
	alias g='git'
fi

# ls
alias la='ls -A'
alias ll='ls -lh'
alias l='ls -alh'
alias lr='ls -R'                    # recursive ls
alias lx='ll -BX'                   # sort by extension
alias lz='ll -rS'                   # sort by size
alias lt='ll -rt'                   # sort by date
alias lm='la | less' 

# ls++
#alias lsp="ls++"
#alias lap="ls++ -A"

# pacman/packer aliases, replace packer/pacman with whichever is used.
alias pac='packer -S'                           # default action                - install one or more packages
alias pacs='packer -Ss'                         # '[s]earch all'                - search aur and regular stream for packages
alias pacsaur='packer -Ss --auronly'            # '[s]earch [aur]'              - search only the aur for packages
alias pacsreg='pacman -Ss'                      # '[s]earch [reg]ular stream'   - search only the regular stream for packages
alias pacrm='sudo pacman -R'                         # '[r]e[m]ove'                  - uninstall one or more packages
alias paci='packer -Si'                         # '[i]nfo'                      - show information about a package
alias pacu='sudo packer -Syu'                        # '[u]pdate'                    - upgrade all packages to newest version
alias pacrlo='sudo sudo pacman -Rs $(pacman -Qtdq)'  # '[r]emove [l]ocal [o]rphans'  - remove all local orphans
alias paccl='sudo pacman -Scc'                  # '[c][l]ear cache              - removes stored files in the cache

# funny commands
# alias ls='sl'

# bash aliases
if [ -f ~/.aliases_personal ]; then
	. ~/.aliases_personal
fi
