#!/bin/bash

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# prompts
#PS1="\u \W " # arch default
PS1='\[\e[0;32m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[1;32m\]\$\[\e[m\] \[\e[0;36m\]' # Fancy colorization


# variables
export EDITOR="vim"

# bash aliases
if [ -f ~/.aliases ]; then
    . ~/.aliases
fi
