#!/bin/sh
# ~/.xinitrc

# Font setup
xset +fp /usr/share/fonts/local
xset fp rehash

# Correct urxvt themeing.
xrdb -merge ~/.Xresources &

#Start daemons and managers
start-pulseaudio-x11
thunar --daemon & #thunar daemon
urxvtd -q -o -f & #urxvt daemon
xscreensaver -no-splash & #screen lock
sleep 20 && dropboxd & #dropbox

# Fix gui java apps displaying in xdisplays
_JAVA_AWT_WM_NONPARENTING=1
export _JAVA_AWT_WM_NONPARENTING

case "$1" in
    fluxbox )
	exec startfluxbox >> ~/.cache/wm_fluxbox_stdout 2> ~/.cache/wm_fluxbox_stderr
	;;
    openbox )
	exec openbox >> ~/.cache/wm_openbox_stdout 2> ~/.cache/wm_openbox_stderr
	;;
    xfce4 )
        exec startxfce4 >> ~/.cache/wm_xfce4_stdout 2> ~/.cache/wm_xfce4_stderr
	;;
    kde )
	exec startkde >> ~/.cache/wm_kde_stdout 2> ~/.cache/wm_kde_stderr
	;;
    gnome )
	exec gnome-session >> ~/.cache/wm_gnome_stdout 2> ~/.cache/wm_gnome_sterr
	;;
    awesome )
	# Set the background
	# awsetbg ~/Pictures/DesktopImg.png
	# ~/wallpaperchanger.sh &
	
	nm-applet & #network manager applet
	xfce4-power-manager & # power manager
	conky -q & #conky
	sleep 4 && urxvtc & #starts a terminal

	# start programs
	# sleep 6 && pidgin & # Pidgin IM client
	exec awesome >> ~/.cache/wm_awesome_stdout 2> ~/.cache/wm_awesome_stderr
	;;
    * )
	exec xterm >> ~/.cache/wm_xorg_stdout 2> ~/.cache/wm_xorg_stderr
esac
