#!/bin/sh
# ~/.xinitrc

# Font setup
xset +fp /usr/share/fonts/local
xset fp rehash

# Correct urxvt themeing.
xrdb -merge ~/.Xresources &

#Start daemons and managers
start-pulseaudio-x11
xfce4-power-manager & #power
thunar --daemon & #thunar daemon
urxvtd -q -o -f & #urxvt daemon
xscreensaver -no-splash & #screen lock
dropboxd & #dropbox

case "$1" in
    cinnamon )
	exec cinnamon >> ~/.cache/cinnamon_wm_stdout 2> ~/.cache/cinnamon_wm_stderr
	;;
    fluxbox )
	exec fluxbox >> ~/.cache/fluxbox_wm_stdout 2> ~/.cache/fluxbox_wm_stderr
	;;
    openbox )
	exec openbox >> ~/.cache/openbox_wm_stdout 2> ~/.cache/openbox_wm_stderr
	;;
    awesome )
        # All else fails start awesome
	#
	# Fix gui java apps displaying in awesome
	_JAVA_AWT_WM_NONREPARENTING=1
	export _JAVA_AWT_WM_NONREPARENTING
	
	# Set the background
	awsetbg ~/Pictures/DesktopImg.png
	~/wallpaperchanger.sh &
	
	nm-applet & #network manager applet
	conky -q & #conky
	sleep 4 && urxvtc & #starts a terminal

	# start programs
	# sleep 6 && pidgin & # Pidgin IM client
	exec awesome >> ~/.cache/awesome_wm_stdout 2> ~/.cache/awesome_wm_stderr
	;;
    * )
	exec xterm >> ~/.cache/xorg_wm_stdout 2> ~/.cache/xorg_wm_stderr
esac
