#!/bin/bash

clear #clears the screen before asking for user-input

# This script was created by Walden Riedel, for use with the Linux Operating System with required package libnotify-bin
# which can be obtained by using command: sudo apt-get install libnotify-bin
# Any questions or comments contact me, war4756@rit.edu, and please include in the subject line "Minecraft Backup helper"
# 
# Thank you.

filetarget="$HOME/.config/minecraftbackup.cfg"
localSave="$HOME/Games/Minecraft/Backup"
localDir=

echo "Welcome to the Minecraft backup helper."


if [ -e $filetarget ]; then
	
	counter=1
	while read line
	do
		if [ $counter -eq 7 ]; then
			localDir=$line
		fi
		let "counter=${counter}+1"
	done < $filetarget
	
        echo -e "Data loaded from saved information, backup directory is: \n$localDir"
	
	echo -e -n "\nDo you want to change the currenty backup directory? [Y/n]: "
	read keypress
	case $keypress in
		 [Yy] ) echo -e "\nPlease enter in the entire path to the directory."
                	read localpath
		        echo -e "DO NOT EDIT THIS FILE!\n\nThis .cfg file is for the minecraft Backup and starter," > $filetarget
			echo -e "this stores the local target of backup location for the backup selector.\n\n" >> $filetarget
			echo $localpath >> $filetarget
			localDir=$localpath
			mkdir -p $localpath/bin/
			echo
			;;
		 * ) echo ;;
	esac
	

else
	localDir=$localSave
	echo "Save file not found, creating one."
        echo -e "DO NOT EDIT THIS FILE!\n\nThis .cfg file is for the minecraft Backup and starter," >> $filetarget
	echo -e "this stores the local target of backup location for the backup selector.\n\n" >> $filetarget
	echo -e -n "Default save directory is\n$localDir\nDo you want to change it now? [Y/n]:"
	read localchange
	case $localchange in 
		[Yy] ) echo -e "Current directory is\n$HOME\nPlease enter in the entire path to the directory."
			read localpath
			localDir=$localpath
			mkdir -p $localpath/bin/
			;;

		[Nn] ) echo "Using last saved directory: $localDir"
			;;

		* ) echo -e "Skipping local path entry, using last saved directory:\n$localDir"
	esac

	echo $localDir >> $filetarget

fi

echo -e -n "Do you want to create a backup? [Y/n]: "
read backup
case $backup in 
	[Yy] ) echo -n "Online, Offline, Both or Quit backup [Y/n/b/Q]: "
		read backupOption
		case $backupOption in
			[Yy] ) echo "Copying Minecraft to online storage."
				rm -R $HOME/Dropbox/.minecraft
				cp -R $HOME/.minecraft/ $HOME/Dropbox/
				
				echo "Saved in $HOME/Dropbox/.minecraft and found at www.Dropbox.com"
				notify-send -t 1000 "Backup finished."
				;;

			[Nn] ) echo -e "\nLocal Backup option."
				desc=
				notify-send -t 1000 "Script requires input."
				echo -n "Please give a description for this backup [Enter for none]: "
				read desc
				Tempdate=`date +%Y"_"%m"_"%d"-"%R"-"%a"-"%b`
				if [ ! -d "$localDir" ]; then
					mkdir -p "$localDir/bin"
				fi
				if [ "${desc}" != "" ]; then
					cp -R $HOME/.minecraft $localDir/"${Tempdate} - ( ${desc} )"
					cp -R $HOME/.minecraft/bin/ $localDir/bin/"${Tempdate} - ( ${desc} )"
					echo "Saved at $localDir/${Tempdate} - ( ${desc} )"
				else
					cp -R $HOME/.minecraft $localDir/"${Tempdate} - ( ... )"
					cp -R $HOME/.minecraft/bin $localDir/bin/"${Tempdate} - ( ... )"
					echo "Saved at $localDir/${Tempdate} - ( ... )"
				fi
				echo "Finished Backing up."
				notify-send -t 1000 "Backup finished."
				;;

			[Bb] ) echo "Copying Minecraft to online storage."
                                rm -R $HOME/Dropbox/.minecraft
                                cp -R $HOME/.minecraft/ ~/Dropbox/

                                echo -e "Saved in $HOME/Dropbox/.minecraft and found at www.Dropbox.com\n"

				desc=
                                echo -n "Please give a description for this backup [Enter for none]: "
                                read desc
                                Tempdate=`date +%Y"_"%m"_"%d"-"%R"-"%a"-"%b`
                                if [ "${desc}" != "" ]; then
                                        cp -R $HOME/.minecraft $localDir/"${Tempdate} - ( ${desc} )"
					cp -R $HOME/.minecraft/bin/ $localDir/bin/"${Tempdate} - ( ${desc} )"
                                        echo "Saved at $localDir/${Tempdate} - ( ${desc} )"
                                else
                                        cp -R $HOME/.minecraft $localDir/"${Tempdate} - ( ... )"
                                        cp -R $HOME/.minecraft/bin/ $localDir/bin/"${Tempdate} - ( ... )"
                                        echo "Saved at $localDir/${Tempdate} - ( ... )"
                                fi
                                echo "Finished Backing up."
                                notify-send -t 1000 "Backup finished."
				;;

			[Qq] ) echo "Quitting Backup Selector."
				notify-send -t 1000 "Skipping Backup."
				;;

			* ) echo "Required input is Y,n,b, or Q to quit"
				exit 1
				;;
		esac

		;;

	[Nn] ) echo -e "\nSkipping Backup."
		notify-send -t 750 "Skipping Backup."
		;;

	* ) echo "Required input is Y and n."
		exit 1
		;;
esac

notify-send -t 1000 "Starting Minecraft"

exec java -Xmx1024M -Xms512M -jar ~/Games/minecraft.jar
clear
exit 0
