#!/bin/bash

clear #clears the screen before asking for user-input

# This script was created by Walden Riedel, for use with the Linux Operating System with required package libnotify-bin
# which can be obtained by using command: sudo apt-get install libnotify-bin
# Any questions or comments contact me, war4756@rit.edu, and please include in the subject line "Minecraft Backup helper"
# 
# Thank you.

filetarget="$HOME/.minecraftbackup.cfg"
localSave="$HOME/Games/Minecraft/Backup"
localDir=

echo "Welcome to the Minecraft backup helper and Minecraft Starter."


if [ -e $filetarget ]; then
	
	counter=1
	while read line
	do
		if [ $counter -eq 7 ]; then
			localDir=$line
		fi
		let "counter=${counter}+1"
	done < $filetarget
	
        echo -e "Data loaded from saved information, backup directory is: \n$localDir\n"
	
	read -s -n1 -t 2 -p "Hit any key in 2 seconds to change the backup directory." keypress
	case $keypress in
		 [a-zA-Z0-9] ) echo -e "\nCurrent directory is\n${localDir}\nPlease enter in the entire path to the directory."
                	read localpath
			#sed '6s/.*/$localpath/' > '$filetarget'
			#perl -pe "s/.*/${localpath}/ if $. == 6" > $filetarget //replaces everything >:@
                	localDir=$localpath
                	#mkdir -p $localpath/bin/ #Don't want to create un-needed folders.
			;;
		 * ) echo ;;
	esac
	

else
	localDir=$localSave
	echo "Save file not found, creating one."
        echo -e "DO NOT EDIT THIS FILE!\n\nThis .cfg file is for the minecraft Backup and starter," >> ~/.minecraftbackup.cfg
	echo -e "this stores the local target of backup location for the backup selector.\n\n" >> ~/.minecraftbackup.cfg
	echo -e -n "Default save directory is\n$localDir\nDo you want to change it now? [Y/n]:"
	read localchange
	case $localchange in 
		[Yy] ) echo -e "Current directory is\n$HOME\nPlease enter in the entire path to the directory."
			read localpath
			localDir=$localpath
			mkdir -p $localpath/bin/
			;;

		[Nn] ) echo "Using last saved directory: $localDir"
			;;

		* ) echo -e "Skipping local path entry, using last saved directory:\n$localDir"
	esac

	echo $localDir >> $HOME/.minecraftbackup.cfg

fi

echo -e -n "\nDo you want to create a backup? [Y/n]: "
read backup
case $backup in 
	[Yy] ) echo -n "Online, Offline, Both or Quit backup [Y/n/b/Q]: "
		read backupOption
		case $backupOption in
			[Yy] ) echo "Copying Minecraft to online storage."
				rm -R $HOME/Dropbox/.minecraft
				cp -R $HOME/.minecraft/ $HOME/Dropbox/
				
				echo "Saved in $HOME/Dropbox/.minecraft and found at www.Dropbox.com"
				notify-send -t 1000 "Backup finished."
				;;

			[Nn] ) echo -e "\nLocal Backup option."
				desc=
				notify-send -t 1000 "Script requires input."
				echo -n "Please give a description for this backup [Enter for none]: "
				read desc
				Tempdate=`date +%Y"_"%m"_"%d"-"%R"-"%a"-"%b`
				if [ ! -d "$localDir" ]; then
					mkdir -p "$localDir/bin"
				fi
				if [ "${desc}" != "" ]; then
					cp -R $HOME/.minecraft $localDir/"${Tempdate} - ( ${desc} )"
					cp -R $HOME/.minecraft/bin/ $localDir/bin/"${Tempdate} - ( ${desc} )"
					echo "Saved at $localDir/${Tempdate} - ( ${desc} )"
				else
					cp -R $HOME/.minecraft $localDir/"${Tempdate} - ( ... )"
					cp -R $HOME/.minecraft/bin $localDir/bin/"${Tempdate} - ( ... )"
					echo "Saved at $localDir/${Tempdate} - ( ... )"
				fi
				echo "Finished Backing up."
				notify-send -t 1000 "Backup finished."
				;;

			[Bb] ) echo "Copying Minecraft to online storage."
                                rm -R $HOME/Dropbox/.minecraft
                                cp -R $HOME/.minecraft/ ~/Dropbox/

                                echo -e "Saved in $HOME/Dropbox/.minecraft and found at www.Dropbox.com\n"

				desc=
                                echo -n "Please give a description for this backup [Enter for none]: "
                                read desc
                                Tempdate=`date +%Y"_"%m"_"%d"-"%R"-"%a"-"%b`
                                if [ "${desc}" != "" ]; then
                                        cp -R $HOME/.minecraft $localDir/"${Tempdate} - ( ${desc} )"
					cp -R $HOME/.minecraft/bin/ $localDir/bin/"${Tempdate} - ( ${desc} )"
                                        echo "Saved at $localDir/${Tempdate} - ( ${desc} )"
                                else
                                        cp -R $HOME/.minecraft $localDir/"${Tempdate} - ( ... )"
                                        cp -R $HOME/.minecraft/bin/ $localDir/bin/"${Tempdate} - ( ... )"
                                        echo "Saved at $localDir/${Tempdate} - ( ... )"
                                fi
                                echo "Finished Backing up."
                                notify-send -t 1000 "Backup finished."
				;;

			[Qq] ) echo "Quitting Backup Selector."
				notify-send -t 1000 "Skipping Backup."
				;;

			* ) echo "Required input is Y,n,b, or Q to quit"
				exit 1
				;;
		esac

		;;

	[Nn] ) echo -e "\nSkipping Backup."
		notify-send -t 750 "Skipping Backup, User input required for login details."
		;;

	* ) echo "Required input is Y and n."
		exit 1
		;;
#
esac

#user=
#password=
#server=

# Maybe save a default user, and last used server?
#
# if "" for user use last used user input.
# if "last" for server use last used server input.
# figure out how to encode/protect the password.

#echo -e -n "\nDo you want to customize login? [Y/n]: "
#read loginOption
#case $loginOption in 
#	[Yy] ) echo -e "Note:\nIf you are entering a password you MUST enter in a username.\n\nThis saves that last known user and server.\nEnter nothing for last used user."
#		# Username Entry #
#		echo -n "Username: "
#		read user
#	
#		# Password Entry #
#		stty -echo
#		echo -e "\nYour password will not be saved, and will be obfuscated."
#		echo -n "Password: "
#		read password
#		stty echo
#	
#		# Server Entry #
#		echo -e "\nFor last known server enter 'last'."
#		echo -n "Server: "
#		read server
#	
#		echo -n "Will run minecraft with user: ${user}"
#		if [ "${server}" != "" ]; then
#			echo ", on server: ${server}."
#			notify-send -t 500 "Starting Minecraft with user: ${user}, on server: ${server}."
#		else
#			echo "."
#			notify-send -t 500 "Starting Minecraft with user: ${user}."
#		fi
#		;;
#
#	[Nn] ) echo -e "\n\nStarting Minecraft."
#		notify-send -t 500 "Starting Minecraft."
#		;;
#
#	* ) echo "Required input is Y and n."
#		exit 1
#		;;
#
#esac

notify-send -t 1000 "Starting Minecraft"

exec java -Xmx1024M -Xms512M -jar ~/Games/minecraft.jar
clear
exit 0
